version: '3.7'

services:
  web:
    build:
      context: containers/web
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
  web_api:
    build:
      context: containers/web-api
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
  batch:
    build:
      context: containers/batch
  redis:
    build:
      context: containers/redis
  mysql:
    build:
      context: containers/mysql
