version: '3.7'

services:
  webfront:
    image: hoge_web
    build:
      context: containers/web
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
    container_name: hoge_web_container
    ports:
      - 80:80
    volumes:
      - ./volumes/web/log:/var/log/nginx
  webback:
    image: hoge_web-api
    build:
      context: containers/web-api
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
    container_name: hoge_web-api_container
    ports:
      - 3000:3000
