root: true
env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - prettier/@typescript-eslint
overrides:
  - files:
      - "*.js"
    rules:
      "@typescript-eslint/no-var-requires": off
      "@typescript-eslint/explicit-function-return-type": off
rules:
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  linebreak-style:
    - 2
    - unix

  block-scoped-var: 2
  consistent-return: 2
  curly: 2
  default-case: 2
  dot-notation: 2
  eqeqeq: 2
  no-eq-null: 2
  no-eval: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-native-reassign: 2
  no-new-wrappers: 2
  no-param-reassign: 2
  no-redeclare: 2
  no-self-compare: 2
  no-throw-literal: 2

  no-console: 2
  no-new: 0
  no-use-before-define: 0
  no-invalid-this: 0
  no-alert: 0
