- name: create network
  docker_network:
    name: common_network
    driver: bridge
    state: present

- name: create image directory
  file:
    path: "{{ system.root_dir}}/images"
    state: directory

- name: copy images
  include_tasks: copy_image.yml
  vars:
    docker_image: "{{ item }}"
  loop: "{{ docker.images }}"
  # with_fileglob: files/images/*.tar

- name: docker-compose
  template:
    src: docker-compose.yml
    dest: "{{ system.root_dir}}"
