---
- name: create users and groups
  block:
    - name: create group
      block:
        - name: create primary group
          group:
            name: "{{ user.group }}"
            gid: "{{ user.gid | default(omit) }}"
          when: user.group is defined
        - name: create secondary groups
          group:
            name: "{{ group }}"
          when: user.groups is defined
          loop: "{{ user.groups }}"
          loop_control:
            loop_var: group

    - name: create user
      user:
        name: "{{ user.name }}"
        uid: "{{ user.uid | default(omit) }}"
        password: "{{ user.password | password_hash('sha512') if user.password is defined else undefined | default(omit) }}"
        update_password: "{{ user.update_password | default('on_create') }}"
        group: "{{ user.group | default(omit) }}"
        groups: "{{ user.groups | default(omit) }}"
        generate_ssh_key: "{{ user.generate_ssh_key | default(false) }}"
        ssh_key_passphrase: "{{ user.ssh_key_passphrase | default(omit) }}"
        home: "{{ user.home | default(omit) }}"
        shell: "{{ user.shell | default(omit) if user.password is defined else '/sbin/nologin' }}"
