all:
  vars:
    ansible_ssh_user: admin
    ansible_become: true
    ansible_become_method: su
    ansible_become_user: root
    system:
      name: test-system
    users:
      - name: test
        password: test01
        generate_ssh_key: true
    docker:
      user: root
      group: root
      root_dir: /opt/docker
  children:
    web:
      hosts:
        web01:
          ansible_host: 192.168.0.13
    db:
      hosts:
        db01:
          ansible_host: 192.168.0.13
