root: true
env:
  browser: true
  es6: true
  node: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
plugins:
  - vue
  - prettier
extends:
  - eslint:recommended
  - plugin:vue/essential
  - plugin:prettier/recommended
rules:
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  linebreak-style:
    - 2
    - unix

  block-scoped-var: 2
  consistent-return: 2
  curly: 2
  default-case: 2
  dot-notation: 2
  eqeqeq: 2
  no-eq-null: 2
  no-eval: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-native-reassign: 2
  no-new-wrappers: 2
  no-param-reassign: 2
  no-redeclare: 2
  no-self-compare: 2
  no-throw-literal: 2

  no-console: 0
  no-new: 0
  no-use-before-define: 0
  no-invalid-this: 0
  no-alert: 0
